### ISSUE TITLE
`id_github_private` absence must not cause failure

### ISSUE THREAD

**Issue by cunnie** [pivotal-sprout/sprout-orchard#1]
The absence of `id_github_private` shouldn't cause a run to fail.

We should consider re-factoring into a shell variable (not sure if this is the right thing)

```
/Users/Shared/Jenkins/Home/workspace/CF Dev Wkstn 10.9.1/lib/util.rb:52:in `system!': ssh pivotal@image-maker-tick 'cp .ssh/id_github_private /Volumes/NEWLY_IMAGED/Users/pivotal/.ssh': 1 (RuntimeError)
    from ./1_reset_machine.rb:65:in `<main>'
```

**Comment by hiremaga** [comment]
@cunnie Is this still an issue?

**Comment by aramprice** [comment]
Closing this, archiving the repo.
